### ISSUE TITLE
Should we use Git submodules or not?

### ISSUE THREAD

**Issue by k-rister** [perftool-incubator/crucible#2]
We want to be able to reference separate repositories in crucible because one of the core design points is to consume many small projects.  One of these reasons to do so is so that individual projects can be managed independently and make progress on difference cadences.  We want to be able to test development code from one project while another project is still on stable code so we intend to use different branches in each repository to signify those different tracts.

The question raised here is should those separate repositories be added to crucible as Git submodules (man git-submodule) and managed as such or should our scripts be responsible for cloning those repositories into the directory structure at runtime (ie. at install/setup).

I'm inclined to think that the Git submodules method would provided the most convenient and robust methodology but we need to ensure that it does not have requirements and/or limitations that prevent us from accomplishing our goals.

**Comment by atheurer** [comment]
Resolved as we have decided to manage git subprojects with the install and update scripts.  Git submodule does not offer the flexibility we need.  If we were to include other git repos which we do not develop ourselves and rarely need versioning updates, then we would consider submodule.
