### ISSUE TITLE
One JSON config file to rule them all

### ISSUE THREAD

**Issue by k-rister** [perftool-incubator/crucible#226]
We want to move toward having a single JSON file that will contain every single piece of information relevant to a Crucible run with the goal eventually being no more command line parameters.  We view this as having the following advantages:

- It will allow us to pass configuration information to all layers of Crucible in a scalable way (through a single file/parameter) rather than constantly forcing us to plumb new parameters through several layers of tools/technologies.
- It will create a single source of truth that describes a run.
- We will be able to 'validate' an entire run's configuration through JSON schema(s).

**Comment by rafaelfolco** [comment]
https://github.com/perftool-incubator/crucible/pull/249
https://github.com/perftool-incubator/crucible/pull/250
https://github.com/perftool-incubator/crucible/pull/251
https://github.com/perftool-incubator/toolbox/pull/55
https://github.com/perftool-incubator/crucible/pull/245
https://github.com/perftool-incubator/crucible/pull/247
https://github.com/perftool-incubator/crucible-ci/pull/55
https://github.com/perftool-incubator/crucible/pull/248

**Comment by k-rister** [comment]
@rafaelfolco Don't forget to add links here if you want to keep track of what all you did for this.
