### ISSUE TITLE
Project installation problems when repos do not exist

### ISSUE THREAD

**Issue by k-rister** [perftool-incubator/crucible#32]
Right now, project repos are assumed to be available from the same user/account Git URL.  This works really well for letting a user test private repos.  However, it means that the user has to have a fork of every project repo to successfully complete an install.  Should we make it fall back on the "master" repo if a user repo doesn't exist?

**Comment by atheurer** [comment]
Yes, we need something to indicate where the original repo is.  We could have a file with this information (keep it under ./config), or we could look at 'git remote -v' for the crucible git and check for "upstream" there, and assume that is the project that should be used for all of the subprojects *which are not present*.

So the process would be
1) get the upstream project location:
-run git remote -v | grep upstream, if not found, check ./config/upstream

2) when cloning the subprojects:
- run git remote -v | grep origin, try to clone from $origin/subproject, if it fails, try $upstream/project, if that fails exit with error

**Comment by k-rister** [comment]
Fixed already
