### ISSUE TITLE
"Release" mechanism for installing "consistent" versions of Crucible

### ISSUE THREAD

**Issue by k-rister** [perftool-incubator/crucible#345]
We need to be able to install a "version" of Crucible that is "locked down" and won't change at all if it is installed many time over many days/weeks/months/etc.

**Comment by k-rister** [comment]
@jtaleric is this an accurate assessment of what you need/want?

**Comment by jtaleric** [comment]
> We need to be able to install a "version" of Crucible that is "locked down" and won't change at all if it is installed many time over many days/weeks/months/etc.

+1 -- locked down, verified, however we want to label it.  This way, folks who want to take advantage of workloads like multi-bench can use an "out of the box" crucible install.

**Comment by k-rister** [comment]
@rafaelfolco Saw this in the todo queue, do you think we can call this done yet?

**Comment by rafaelfolco** [comment]
> @rafaelfolco Saw this in the todo queue, do you think we can call this done yet?
I guess so
