### ISSUE TITLE
--output-format stops printing a valid .json

### ISSUE THREAD

**Issue by sferlin** [perftool-incubator/crucible#414]
When calling crucible as follows:

`crucible get metric --source mpstat --type Busy-CPU --period <period-ID> --breakout hostname,num --output-format json
`

It suddenly stops printing a valid .json if **not** filtered by a specific hostname.

```
{
  "values": {
    "<hostname0>-<0>": [
      {
        "begin": 1728293815960,
        "end": 1728293935954,
        "value": 0.010457660735863994
      }
    ],

(...)

    "<hostname0>-<74>": [
      {
        "begin": 1728293815960,
        "end": 1728293935954,
        "value": 0.01779547647818659
      }
    ],
    "<hostname0>-<75>": [
      {
        "begin": 1728293815960,
        "end": 1728293935954,
        "value"

```

**Comment by sferlin** [comment]
You can close/park this issue somewhere. I will keep the data next time.

**Comment by k-rister** [comment]
I'm going to close this issue for now.  If it reoccurs just reopen it and we can revisit the problem.
