### ISSUE TITLE
When ES is started, the index templates need to be created if they do not already exists in the instance

### ISSUE THREAD

**Issue by atheurer** [perftool-incubator/crucible#64]
Whenever ES is started, we need to check to see if the index templates and base indices are present, and if not, automatically create them.  This is critical that this is done before any documents are added to the instance, as adding those documents without the proper mappings will result in incorrect mappings which cannot easily be altered.

**Comment by atheurer** [comment]
This is a little tricky to do at es-start because we launch a container to start ES, and while that container is detached from the calling terminal, inside the container the ES process is running in the foreground.  So, there is not a good opportunity to connect to the ES service and check for templates & indices during this launch process.

We may want to wait for the ES container to be ready (the process is listening on port 9200), then launch a container just for the initialization of the templates & indices.  We might want to do this after a little bit of time has passed, but not delay progress of other work.  For example, when kicking off a new crucible run, we launch ES if not present, then launch http if not present, then launch a container to run the test.  We could launch an "init-es" container after the http container, and hopefully enough time has already passed that ES is already listening on port 9200, and there is no explicit wait (sleep) for the service.

**Comment by k-rister** [comment]
Are we using a custom ES container or one provided by somebody (via a container registry)?

If it's custom, why wouldn't we just plumb the startup script with the bits necessary to ensure this is being taken care of?

**Comment by atheurer** [comment]
All of the crucible services come from the crucible-controller container we define with a workshop json.  There are no "third-party" containers at all.

We can customize whatever we want.  However, the way we have it now is the ES process runs in the foreground of the container, but since the container is detached, the effect to the user is it looks like a service, aka daemonized.  In order to do more work beyond starting ES [within the same container], we would need to daemonize it _inside_ the container.  If we want to daemonize it, then we will need to implement some kind of init script/solution, then launch the ES service, then launch a script the do the templating and indexing.

I was trying to keep the process of starting these services like ES, redis, http, fairly simple, so I did not take that approach, but we could consider it.  For now I think we'll just launch a templating script via container right after ES is started.  If we want to daemonize these services within the container, we should come up with an approach and implement for all the services we use.

**Comment by k-rister** [comment]
Does this mean we are running a unique container for every single one of these services?

**Comment by atheurer** [comment]
> Does this mean we are running a unique container for every single one of these services?

Yes.

**Comment by k-rister** [comment]
Ok, that explains why nothing is daemonized inside the container(s).  One more question, how are you making sure that container X knows how to talk to container Y?

**Comment by atheurer** [comment]
> Ok, that explains why nothing is daemonized inside the container(s). One more question, how are you making sure that container X knows how to talk to container Y?

They always use host-network.

**Comment by k-rister** [comment]
Does that mean they just can always attempt to connect to "localhost" to reach one of the other services?

**Comment by atheurer** [comment]
Yes, all services are accessible via localhost, wether or not a client is trying to reach that service.  We will probably make elasticsearch only listen to localhost instead of all interfaces, as it basically has no security.  Other services like redis, http, can be reached from any interface.

**Comment by atheurer** [comment]
This should already be taken care of with init_es() in _main
