### ISSUE TITLE
Provide crucible command to add or remove tags to a run

### ISSUE THREAD

**Issue by atheurer** [perftool-incubator/crucible#67]
We need the ability to very easily add or remove a tag to a run.  Tags are used to help annotate a run with certain characteristics, like a project it is a part of, or a specific network topology, or really anything to help a user find this run and distinguish it from another run.

This should be as easy as:
crucible result --tag <field:value> [--run <run-id> or --base-run-dir <path>]
crucible result --untag <field:value> [--run <run-id> or --base-run-dir <path>]

When use runs a command like this, crucible must use the CommonDataModel subproject to alter the ES documents to add or remove the tag, and needs to use rickshaw subproject to add/remove the tag from the rickshaw-result.json file found in $base_run_dir/run/

**Comment by k-rister** [comment]
already done
