### ISSUE TITLE
Should executables that are not meant to be called by an end user be moved into a private bin directory?

### ISSUE THREAD

**Issue by k-rister** [perftool-incubator/crucible#8]
That way when an end user looks at the bin directory they only see stuff that is applicable to them?

**Comment by atheurer** [comment]
I would hope the user never looks at the crucible/bin dir and only pays attention to /usr/bin/crucible.  None of the other scripts in crucible/bin should have symlinks to /usr/bin/, so they should not execute by accident(?).  I suppose we can hide them or put them in a dir that indicates they should not be executed directly, but I wonder if that will really stop the determined end user...

**Comment by k-rister** [comment]
The way you have setup the installer now I don't think this is an issue worth spending time on.  A "normal" user will probably never look at the bin directory and as you said a "determined" user would find the stuff no matter what.  Plus, splitting stuff up just adds overhead in development/management of the project.  I'm fine with closing this if you are.
