### ISSUE TITLE
running the install script blows away /etc/sysconfig/crucible

### ISSUE THREAD

**Issue by k-rister** [perftool-incubator/crucible#97]
https://github.com/perftool-incubator/crucible/blob/fe1e8bc6f8ab416fa8ea9fb71d069e83f1126e5d/bin/install#L36

**Comment by k-rister** [comment]
I ran the installer in order to pull down a new repository down that I'm working on adding.  After running the installer my crucible installation was broken and was only fixed by restoring /etc/sysconfig/crucible.  We probably need to give the install script an update given the new container/install procedures.

**Comment by k-rister** [comment]
@atheurer FYI...

**Comment by atheurer** [comment]
I did the exact same thing yesterday...

**Comment by atheurer** [comment]
Fixed with #105
